<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
// Passes purchase total from customer session to Facebook pixel dashboard

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<?php // Checks that the module is enabled and revenue tracking is enabled. ?>
<?php if ($this->snippet->getIsEnabled() && $this->getTrackRevenue()): ?>
	<script type="text/javascript">
	    fbq('track', 'Purchase', {'value':<?php print $block->getRevenue(); ?>,'currency':'USD'});
	</script>
<?php endif; ?>