<?php

/**
 * Augustash Facebook Pixel
 *
 * Adds the meta pixel tracking script to the HTML head section
 *
 * @author Josh Johnson <josh@augustash.com>
 * @author Adam Cornell <acornell@augustash.com>
 * @copyright 2025 - present August Ash, Inc. (https://augustash.com)
 */

declare(strict_types=1);

use Augustash\Facebookpixel\Block\Blocks;
use Magento\Framework\Escaper;

/** @var Blocks $block */
/** @var Escaper $escaper */
?>

<?php // Checks that the module is enabled and revenue tracking is enabled. ?>
<?php if ($block->isTrackRevenueEnabled()): ?>
    <script>
        fbq('track', 'Purchase', {'value':<?= $escaper->escapeHtml($block->getRevenue()); ?>,'currency':'USD'});
    </script>
<?php endif; ?>
